課題3.4.1 実行済み
課題3.4.2 8, 10行目に定義してある
課題3.4.3 
課題3.4.4
self.initial_maze = [[1, 1, 1, 1],
                     [1, 1, 0, 1],
                     [1, 1, 1, 1]]
から
self.initial_maze = [[1, 1, 1, 1],
                     [1, 1, 0, 0],
                     [1, 1, 1, 1]]
課題3.4.9まででmain.pyを編集しすぎたので分けた。
課題3.4.10は普通に動いた。
